server:
  port: 9094

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/microservice?allowPublicKeyRetrieval=true&useSSL=false
    username: root
    password: password
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
    hibernate:
      ddl-auto: update
    show-sql: true

logging:
  level:
    root: INFO
